---
- hosts: test
  become: yes
  become_method: sudo

  tasks:
  - name: Install Docker Repo
    yum_repository: 
      name: Docker Repository 
      baseurl: https://yum.dockerproject.org/repo/main/centos/6
      enabled: 1
      gpgcheck: 1
      gpgkey: https://yum.dockerproject.org/gpg
      dest: /etc/yum.repos.d/docker.repo

  - name: Install Docker Engine
    yum: name=docker-engine state=present

  - name: Start Docker service
    service: name=docker state=running enabled=true
