---
- hosts: test

  tasks:

  - name: copy docker.repo
    copy:
      src: docker.repo
      dest: /etc/yum.repos.d/docker.repo
      owner: root
      group: root
      mode: 0644

  - name: Install Docker Engine
    sudo: yes
    yum: name=docker-engine state=present

  - name: Start Docker service
    service: name=docker state=running enabled=true
