---
- hosts: test
  become: yes
  become_method: sudo
  tasks:
 
  -   name: Install python setup tools
      yum: name=python-setuptools

  -   name: Install Pypi
      easy_install: name=pip state=latest

  -   name: Install docker-py
      pip: name=docker-py

  -   name: Install docker-io
      yum: name=docker-io state=present

  -   name: Start Docker service
      service: name=docker state=started
